name: Dev Notes to Discord

on:
  push:
    branches:
      - main # track main branch; add others if needed

jobs:
  post-discord:
    runs-on: ubuntu-latest
    steps:
      - name: Post commits to Discord with embeds
        run: |
          webhook_url="${{ secrets.DISCORD_DEV_NOTES_WEBHOOK }}"
          commits="${{ toJSON(github.event.commits) }}"
          branch="${{ github.ref_name }}"
          
          if [ -z "$commits" ] || [ "$commits" = "[]" ]; then
            echo "No commits to post"
            exit 0
          fi
          
          # Create JSON payload
          payload=$(cat <<EOF
          {
            "embeds": [
              {
                "title": "ðŸ“ New commits pushed",
                "description": "Branch: **$branch**",
                "color": 3066993,
                "fields": [
          EOF
          )
          
          first=true
          echo "$commits" | jq -r '.[] | @base64' | while read commit; do
            commit_data=$(echo "$commit" | base64 -d | jq -r '.author.name, .message, .url')
            author=$(echo "$commit_data" | sed -n '1p')
            message=$(echo "$commit_data" | sed -n '2p')
            url=$(echo "$commit_data" | sed -n '3p')
            
            if [ "$first" = true ]; then
              payload="${payload}{\"name\":\"$author\",\"value\":\"[$message]($url)\"}"
              first=false
            else
              payload="${payload},{\"name\":\"$author\",\"value\":\"[$message]($url)\"}"
            fi
          done
          
          payload="${payload}],\"footer\":{\"text\":\"GospelGo Dev Notes\"},\"timestamp\":\"$(date -Iseconds)\"}]}"
          
          curl -X POST "$webhook_url" \
            -H "Content-Type: application/json" \
            -d "$payload"
